site_name: Perseo Context-aware Complex Event Processing
site_description: Perseo Documentation
repo_url: https://github.com/telefonicaid/perseo-fe
theme: readthedocs
extra_css: ['https://www.fiware.org/style/fiware_readthedocs_processing.css']

pages:
- 'Introduction': 'index.md'
- 'Architecture': 'architecture/architecture.md'
- 'Admin Guide': 'admin/index.md'
- 'User Guide': 'user/index.md'
- 'O&M':
    - 'Deployment': 'admin/deployment.md'
    - 'Configuration': 'admin/configuration.md'
    - 'Administration': 'admin/admin.md'
    - 'Metrics API': 'API/metrics_api.md'
    - 'Logs & Alarms': 'admin/logs.md'
- 'API':
    - 'API': 'API/api.md'
    - 'Actions': 'API/pep_actions.md'
    - 'Plain rules': 'API/plain_rules.md'
    - 'Errors': 'API/errors.md'
- 'Data model': 'models/models.md'
- 'Documentation for developers of perseo': 'developer/development.md'
- 'Roadmap': 'roadmap.md'

markdown_extensions:
    - markdown.extensions.tables
    - toc:
        permalink: True
        separator: "-"
